### ISSUE TITLE
["Bug"] Ampersand in module name isn't rendered properly

### ISSUE THREAD

**Issue by tagnullde** [Daxiongmao87/foundry-vtt-5e-phb-journal-styling#5]
A screenshot says more than a thousand words. ;)

![image](https://user-images.githubusercontent.com/44159008/131003885-7269d6b4-ae06-4db3-9e48-c8c415c2b75c.png)

**Comment by Daxiongmao87** [comment]
Oh that's interesting.  I'll look into this, thank you :)

**Comment by tagnullde** [comment]
Just learned it seems to be a core issue and it's being worked on I guess.

https://gitlab.com/foundrynet/foundryvtt/-/issues/5738

**Comment by Daxiongmao87** [comment]
Thank you for the follow-up :) I'll close this ticket since the issue seems to be elsewhere.
