### ISSUE TITLE
Module not showing up on Module Settings

### ISSUE THREAD

**Issue by ghost** [Daxiongmao87/foundry-vtt-5e-phb-journal-styling#6]
I've installed the module but it's not showing up in my Module Settings page.

![2021-09-22_18-55-12](https://user-images.githubusercontent.com/30846057/134437219-5f8eefbd-6492-423f-bf65-b3f2d1086b51.png)

I have other modules installed, but have disabled them to make sure it's not some kind of conflict:

![image](https://user-images.githubusercontent.com/30846057/134437306-2b0be9fd-8aca-41cd-af98-8ba8d950ba1f.png)

I even downgraded my Foundry installation to 0.8.8 to make sure there wasn't a version incompatibility. 

Any thoughts?

**Comment by Daxiongmao87** [comment]
Hello.  There isn't a settings page for this module.  What sort of settings would you like to have seen?

**Comment by ghost** [comment]
Good morning,

I was going by the instructions in the readme file.

![image](https://user-images.githubusercontent.com/30846057/134510471-31df2941-c32d-4646-818e-c13921dddf89.png)

It seemed to me that if it wasn't working according to the instructions, something was amiss.

If the current version doesn't work like that, perhaps it's time to update the instructions to reflect the current version?

Thanks,

Morgan

**Comment by Daxiongmao87** [comment]
Hey Morgan,
Which step are you having issues with here?  I do not see Module Settings being mentioned, but just step number 5 referring to the Settings tab, and Manage Modules.  This step is necessary to enable the module, and your first screenshot shows that you have done that.

Module Settings is where modules allow users to further configure a module, while Module Management within the Settings tab allows users to enable or disable modules.  Currently, this module does not have any extra settings to be configured in Module Settings, but it still needs to be enabled via the Module Management window within the Settings tab, just like any other module.

Hope this helps.

**Comment by ghost** [comment]
Argh!!!

Never mind.

Please pretend I never sent that message :)

You are entirely correct, and I read it wrong. I am very sorry to have
wasted your time. Can we pretend this never happened?

Thanks,

Morgan

**Comment by Daxiongmao87** [comment]
No worries at all! I'll go ahead and close this if you're satisfied!  Glad we were able to solve this :)
